<?php
declare(strict_types=1);

/**
 * Handles import and export of meta box configurations via the admin UI.
 *
 * Extracted from ActionHandler to keep each handler under 200 lines.
 *
 * @package CustomMetaBoxBuilder
 * @since   2.0
 */

namespace CMB\Core\AdminUI;

defined( 'ABSPATH' ) || exit;

class ImportExportHandler {
    /**
     * Handle JSON export of field group configurations.
     */
    public static function handleExport(): void {
        if (empty($_GET['cmb_export']) || empty($_GET['page']) || $_GET['page'] !== 'cmb-builder') {
            return;
        }
        if (!current_user_can('manage_options')) {
            return;
        }

        $exportId = sanitize_text_field($_GET['cmb_export']);
        $configs  = ActionHandler::getConfigs();

        if ($exportId === 'all') {
            if (!wp_verify_nonce($_GET['_wpnonce'] ?? '', 'cmb_export_all')) {
                return;
            }
            $data = $configs;
            $filename = 'cmb-all-field-groups-' . gmdate('Y-m-d') . '.json';
        } else {
            if (!wp_verify_nonce($_GET['_wpnonce'] ?? '', 'cmb_export_' . $exportId)) {
                return;
            }
            if (!isset($configs[$exportId])) {
                return;
            }
            $data = [$exportId => $configs[$exportId]];
            $filename = 'cmb-' . $exportId . '-' . gmdate('Y-m-d') . '.json';
        }

        // SEC-N01: Strip CRLF from filename to prevent header injection.
        $filename = str_replace(["\r", "\n"], '', $filename);

        $export = [
            'version'      => '2.0',
            'plugin'       => 'custom-meta-box-builder',
            'exported_at'  => gmdate('Y-m-d\TH:i:s\Z'),
            'field_groups' => $data,
        ];

        $json = wp_json_encode($export, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        header('Content-Type: application/json');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($json));
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        echo $json;
        exit;
    }

    /**
     * Handle PHP code export of a single field group configuration.
     */
    public static function handleExportPhp(): void {
        if (empty($_GET['cmb_export_php']) || empty($_GET['page']) || $_GET['page'] !== 'cmb-builder') {
            return;
        }
        if (!current_user_can('manage_options')) {
            return;
        }

        $exportId = sanitize_text_field($_GET['cmb_export_php']);
        if (!wp_verify_nonce($_GET['_wpnonce'] ?? '', 'cmb_export_php_' . $exportId)) {
            return;
        }

        $configs = ActionHandler::getConfigs();
        if (!isset($configs[$exportId])) {
            return;
        }

        $box = $configs[$exportId];
        $fields = var_export($box['fields'] ?? [], true);
        $postTypes = var_export($box['postTypes'] ?? ['post'], true);

        $php = "<?php\n";
        $php .= "// Generated by Custom Meta Box Builder on " . gmdate('Y-m-d') . "\n\n";
        $php .= "add_custom_meta_box(\n";
        $php .= "    " . var_export($exportId, true) . ",\n";
        $php .= "    " . var_export($box['title'] ?? '', true) . ",\n";
        $php .= "    " . $postTypes . ",\n";
        $php .= "    " . $fields . ",\n";
        $php .= "    " . var_export($box['context'] ?? 'advanced', true) . ",\n";
        $php .= "    " . var_export($box['priority'] ?? 'default', true) . "\n";
        $php .= ");\n";

        $filename = 'cmb-' . $exportId . '.php';
        // SEC-N01: Strip CRLF from filename to prevent header injection.
        $filename = str_replace(["\r", "\n"], '', $filename);
        header('Content-Type: application/x-php');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($php));
        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
        header('Pragma: no-cache');
        echo $php;
        exit;
    }

    /**
     * Handle JSON import of field group configurations.
     */
    public static function handleImport(): void {
        if (empty($_POST['cmb_action']) || $_POST['cmb_action'] !== 'import') {
            return;
        }
        if (!isset($_POST['cmb_import_nonce']) || !wp_verify_nonce($_POST['cmb_import_nonce'], 'cmb_import')) {
            return;
        }
        if (!current_user_can('manage_options')) {
            return;
        }

        $json = '';
        if (!empty($_FILES['cmb_import_file']['tmp_name'])) {
            $fileSize = $_FILES['cmb_import_file']['size'] ?? 0;
            if ($fileSize > 1024 * 1024) {
                wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
                exit;
            }
            $json = file_get_contents($_FILES['cmb_import_file']['tmp_name']);
        } elseif (!empty($_POST['cmb_import_json'])) {
            $json = wp_unslash($_POST['cmb_import_json']);
            if (strlen($json) > 1024 * 1024) {
                wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
                exit;
            }
        }

        if (empty($json)) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=no_data'));
            exit;
        }

        $data = json_decode($json, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=invalid_json'));
            exit;
        }

        // SEC-N04: Validate required keys exist in import schema.
        if (!isset($data['meta_boxes']) && !isset($data['field_groups'])) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
            exit;
        }
        if (isset($data['meta_boxes']) && !is_array($data['meta_boxes'])) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
            exit;
        }
        if (isset($data['field_groups']) && !is_array($data['field_groups'])) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
            exit;
        }

        // Support both v1 (meta_boxes) and v2 (field_groups) format
        $groups = $data['field_groups'] ?? $data['meta_boxes'] ?? null;
        if (empty($groups) || !is_array($groups)) {
            wp_safe_redirect(admin_url('admin.php?page=cmb-builder&error=import_failed'));
            exit;
        }

        $configs = ActionHandler::getConfigs();
        $count   = 0;

        foreach ($groups as $id => $box) {
            if (empty($box['title'])) {
                continue;
            }
            $configs[$id] = [
                'title'        => sanitize_text_field($box['title']),
                'postTypes'    => array_map('sanitize_text_field', $box['postTypes'] ?? ['post']),
                'fields'       => self::sanitizeImportedFields($box['fields'] ?? []),
                'context'      => sanitize_text_field($box['context'] ?? 'advanced'),
                'priority'     => sanitize_text_field($box['priority'] ?? 'default'),
                'active'       => $box['active'] ?? true,
                'show_in_rest' => $box['show_in_rest'] ?? false,
            ];
            $count++;
        }

        ActionHandler::saveConfigs($configs);

        wp_safe_redirect(admin_url('admin.php?page=cmb-builder&imported=' . $count));
        exit;
    }

    /**
     * SEC-R01: Deep recursive sanitization for arbitrary imported field data.
     */
    public static function sanitizeFieldsDeep(array $fields): array {
        return array_map(function($field) {
            if (is_array($field)) {
                return self::sanitizeFieldsDeep($field);
            }
            return is_string($field) ? sanitize_text_field($field) : $field;
        }, $fields);
    }

    /**
     * Sanitize an array of imported fields with structured processing.
     *
     * @param array $fields Raw imported fields.
     * @return array Sanitized fields.
     */
    public static function sanitizeImportedFields(array $fields): array {
        // SEC-R01: Apply deep sanitization before structured processing.
        $fields = self::sanitizeFieldsDeep($fields);

        $sanitized = [];
        foreach ($fields as $field) {
            if (!is_array($field) || empty($field['id'])) {
                continue;
            }
            $clean = [
                'id'            => sanitize_text_field($field['id']),
                'type'          => sanitize_text_field($field['type'] ?? 'text'),
                'label'         => sanitize_text_field($field['label'] ?? ''),
                'description'   => sanitize_text_field($field['description'] ?? ''),
                'required'      => !empty($field['required']),
                'placeholder'   => sanitize_text_field($field['placeholder'] ?? ''),
                'default_value' => sanitize_text_field($field['default_value'] ?? ''),
                'width'         => sanitize_text_field($field['width'] ?? ''),
            ];

            // Numeric fields
            if (isset($field['rows']))     $clean['rows']     = intval($field['rows']);
            if (isset($field['min']))      $clean['min']      = sanitize_text_field((string)($field['min'] ?? ''));
            if (isset($field['max']))      $clean['max']      = sanitize_text_field((string)($field['max'] ?? ''));
            if (isset($field['step']))     $clean['step']     = sanitize_text_field((string)($field['step'] ?? ''));
            if (isset($field['min_rows'])) $clean['min_rows'] = intval($field['min_rows']);
            if (isset($field['max_rows'])) $clean['max_rows'] = intval($field['max_rows']);

            // Relational fields
            if (!empty($field['post_type'])) $clean['post_type'] = sanitize_text_field($field['post_type']);
            if (!empty($field['taxonomy']))  $clean['taxonomy']  = sanitize_text_field($field['taxonomy']);
            if (!empty($field['role']))      $clean['role']      = sanitize_text_field($field['role']);

            // Boolean flags
            if (!empty($field['repeatable'])) $clean['repeatable'] = true;
            if (isset($field['collapsed']))   $clean['collapsed']  = (bool)$field['collapsed'];

            // Options (select/radio)
            if (!empty($field['options']) && is_array($field['options'])) {
                $opts = [];
                foreach ($field['options'] as $k => $v) {
                    $opts[sanitize_text_field((string)$k)] = sanitize_text_field((string)$v);
                }
                $clean['options'] = $opts;
            }

            // Recursively sanitize sub-fields for groups
            if (!empty($field['sub_fields']) && is_array($field['sub_fields'])) {
                $clean['sub_fields'] = self::sanitizeImportedFields($field['sub_fields']);
            }
            if (!empty($field['fields']) && is_array($field['fields'])) {
                $clean['fields'] = self::sanitizeImportedFields($field['fields']);
            }

            // Remove empty values to keep storage clean
            $clean = array_filter($clean, function ($v) {
                return '' !== $v && null !== $v && 0 !== $v;
            });
            // Always keep id and type
            $clean['id']   = sanitize_text_field($field['id']);
            $clean['type'] = sanitize_text_field($field['type'] ?? 'text');

            $sanitized[] = $clean;
        }
        return $sanitized;
    }
}
